import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/layout/header/header-top-home/header-top";
import { CartProvider } from "@/components/cart/cart-context";
import CartSidebar from "@/components/cart/cart-sidebar";
import { ToastProvider } from "@/components/providers/toast-provider";
import { WishlistProvider } from "@/components/wishlist/wishlist-context";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <WishlistProvider>
        <CartProvider>
          <HeaderTop />
          <main className="bg-gray-100">{children}</main>
          <CartSidebar />
          <ToastProvider />
          
        </CartProvider>
        </WishlistProvider>
        
      </body>
    </html>
  );
}